server:
  port: 8088
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hand_springboot_exam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B7
    username: root
    password: katasandi
mybatis:
  type-aliases-package: com.hand.training.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.hand.training: debug
    com.ibatis.UserMapper: DEBUG
